#!/bin/bash
usage () {
    echo "Usage: $0 [-k] [-q|--enqueue]"
    echo
    echo "Options:"
    echo "  -k: Use KVM for the simulations."
    echo "  -q, --enqueue: Enqueue the generated simulations to slurm."
}

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
SCRIPT_COMMAND="$0"
set -o nounset
set -o pipefail
set -o errexit
trap 'echo "$SCRIPT_COMMAND: error $? at line $LINENO"' ERR

CONFIG_FILE="$SCRIPT_DIR/config.chats.retry.sensibility.py"


GEN_SCRIPTS="$SCRIPT_DIR/../run-scripts/gem5_gen_scripts.py" 
GEN_SCRIPTS_ARGS=("--config-file" "$CONFIG_FILE")

while getopts "kq-:" opt; do
    case "$opt" in
        -)
            case "${OPTARG}" in
                enqueue)
                    GEN_SCRIPTS_ARGS=("${GEN_SCRIPTS_ARGS[@]}" "--enqueue" )
                    ;;
                *)
                    echo "Invalid option: --$OPTARG" >&2
                    usage
                    exit 1
                    ;;
            esac
            ;;
        q)
            GEN_SCRIPTS_ARGS=("${GEN_SCRIPTS_ARGS[@]}" "--enqueue" )
            ;;
        k)
            export KVM_ACTIVE="true"
            ;;
        *)
            echo "Invalid option: -$OPTARG" >&2
            usage
            exit 1
            ;;
    esac
done


# This environment variable is used by $CONFIG_FILE
export OUTPUT_DIR="${OUTPUT_DIR:-$(realpath "$SCRIPT_DIR/../../../results/chats-retry-sens")}"


[[ -n "${OUTPUT_DIR:-}" && -e "$OUTPUT_DIR" ]] && {
    echo "Output directory «$OUTPUT_DIR» already exists. Delete it or use another."
    exit 1;
}

"$GEN_SCRIPTS" "${GEN_SCRIPTS_ARGS[@]}"